import Head from "next/head";
import UserList from "@/components/user/userList";
import { GetServerSideProps, NextPage } from "next";
import { UserType } from "@/types/userTypes";
import { useRouter } from "next/router";
import { useState } from "react";
import Header from "@/components/header";
export interface HomeProps {
  serverData: UserType[];
}
const Home: NextPage<HomeProps> = ({ serverData }) => {
  const router = useRouter();
  const [userList, setUserList] = useState<UserType[]>(serverData);

  const deleteUserByIdState = (id: string): void => {
    setUserList(userList.filter((user) => user._id !== id));
  };
  const deleteUserById = async (id: string) => {
    const response = await fetch(`http://localhost:3000/api/student/${id}`, {
      method: "DELETE",
    });

    if (!response.ok) {
      throw new Error("User is not delete.");
    }
    deleteUserByIdState(id);
    return response.json();
  };

  if (router.isFallback) {
    return (
      <>
        <div>Loading....</div>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setUserList={setUserList} userList={userList} />
      <main>
        <UserList deleteUserById={deleteUserById} data={userList} />
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const response = await fetch("http://localhost:3000/api/student");
  const data = await response.json();

  return {
    props: {
      serverData: data.data,
    },
  };
};

export default Home;
